# Copyright 2016 by Fred George. May be copied with this notice.

# Partly inspired by https://rubyplus.com/articles/2461

FROM fredgeorge/ruby_w_runit:latest
MAINTAINER Fred George "fredgeorge@acm.org"

RUN gem install rack
RUN gem install rack-test
RUN gem install sinatra
RUN gem install thin
