# Copyright 2016 by Fred George. May be copied with this notice.

# Dockerfile to build a Node.js environment with NVM

FROM node:latest
MAINTAINER Fred George "fredgeorge@acm.org"

RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.31.4/install.sh | bash
