# Copyright 2016 by Fred George. May be copied with this notice.

FROM fredgeorge/ruby_w_runit:latest
MAINTAINER Fred George "fredgeorge@acm.org"

RUN gem install rspec
RUN gem install sequel
RUN gem install mysql2
RUN gem install sinatra
RUN gem install sinatra-contrib
