# Copyright 2016 by Fred George. May be copied with this notice.

# Dockerfile to build a Ruby runtime for Rental Car Offers microservices

FROM fredgeorge/ruby_w_runit
MAINTAINER Fred George "fredgeorge@acm.org"

RUN gem install json
RUN gem install pry
RUN gem install pry-nav
RUN gem install bunny
