# Copyright 2016 by Fred George. May be copied with this notice.

FROM fredgeorge/ruby_w_runit:latest
MAINTAINER Fred George "fredgeorge@acm.org"

RUN gem install bundler
RUN gem install rails
RUN gem install therubyracer
